#!/bin/bash
misaki="misaki-gothic.txt"
incls="$(sed -n 's/^INCLUDE \([^ ]*\.txt\).*$/\1/p' unscii.txt | grep -vFx extra-misaki.txt)"
output="extra-misaki.txt"

echo $incls

(
	echo 'generated by make-extra-misaki.sh'
	echo
	echo ===
	echo
	for i in $(grep -o '^U+[^\s]*' $misaki |less)
	do
		if ! grep $i $incls > /dev/null
		then
			grep $i $misaki -A9
			echo
		fi
	done
) > $output

